baseurl = "http://tamasgal.com/"
relativeurls = false

languageCode = "en-us"
title = "Tamás Gál"
disqusShortname = "tamasgal"

pygmentsUseClasses = true
pygmentsCodeFences = true 

[permalinks]
    blog = "/:filename/"

[taxonomies]
    tag = "tags"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = ""
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    pre = "edit"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "macOS"
    pre = "monitor"
    url = "/mac/"
    weight = 3
#  [[menu.main]]
#    name = "Physics"
#    pre = "monitor"
#    url = "/physics/"
#    weight = 4
  [[menu.main]]
    name = "Tetris"
    pre = "grid"
    url = "/tetris/"
    weight = 4
  [[menu.main]]
    name = "Groooo"
    pre = "circle"
    url = "/groooo/"
    weight = 5
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 6
  [[menu.main]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/tamasgal"
    weight = 9
  [[menu.main]]
    name = "Twitter"
    pre = "twitter"
    url = "https://twitter.com/tamasgal"
    weight = 9

[params]
    homeText = "You just made Hugo from scratch."
    dateFormat = "2006-01-02"
